version: 2
jobs:
  build:
    docker:
        - image: ramonsaraiva/pubg-python:0.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
